# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Exploring the Enchanting Wonders of Indonesian Tourism and Culture
email: marchelinjesica@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to our blog, where we embark on a fascinating journey to unravel the mystical allure of Indonesia's tourism and rich cultural heritage. Situated in Southeast Asia, this archipelago is renowned for its stunning landscapes, diverse traditions, and warm hospitality. Join us as we showcase the hidden gems, vibrant traditions, and captivating experiences that make Indonesia a must-visit destination for every traveler and culture enthusiast.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jesica_elizabeth03
github_username:  jesica_elizabeth03

# Build settings
markdown: kramdown
theme: jekyll-theme-architect
plugins:
  - jekyll-feed
  
permission:
  id-token: write
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
